image: python:3.7.3

pipelines:
  default:
    - step:
        name: install dependencies and make project
        caches:
          - pip
        script:
          - uname -a
          - apt-get update
          - apt-get --yes install make pandoc
          - pip3 install -r requirements.txt
          - pip3 list
          - make check test run
