---
name: Python application

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: setup
        run: |
          python -m pip install --upgrade pip virtualenv
          python -m virtualenv venv
          source venv/bin/activate
          pip install -Ur requirements.txt
          python --version
          pip --version
          virtualenv --version
          echo isort $(isort --version-number)
          black --version
          flake8 --version
          pylint --version
          yamllint --version

      - name: check
        run: |
          source venv/bin/activate
          isort --check --diff \
            read_yaml.py employees/*.py utils/*.py tests/*.py
          sort-requirements --check requirements.txt
          black --check \
            read_yaml.py employees/*.py utils/*.py tests/*.py
          pylint \
            read_yaml.py employees/*.py utils/*.py tests/*.py
          yamllint --strict tests/*.yaml

      - name: test
        run: |
          source venv/bin/activate
          pytest -v --cov-report term-missing --cov=employees tests/

      - name: run
        run: |
          source venv/bin/activate
          python -m read_yaml -h
          python -m read_yaml --version
          python -m read_yaml -v tests/test.yaml

      - name: document
        run: |
          source venv/bin/activate
          pytest -v --html=cover/report.html \
            --cov=employees --cov-report=html:cover tests/
          coverage html -d cover employees/employees.py
          (cd docs; make html)

      - name: publish
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/docs/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
